package com.example.collectionsapp.data.repository

import com.example.collectionsapp.data.database.dao.CollectionDao
import com.example.collectionsapp.data.database.dao.CollectionItemDao
import com.example.collectionsapp.data.database.entities.Collection
import com.example.collectionsapp.data.database.entities.CollectionItem
import kotlinx.coroutines.flow.Flow

class CollectionRepository(
    private val collectionDao: CollectionDao,
    private val collectionItemDao: CollectionItemDao
) {
    // Collection operations
    fun getAllCollections(): Flow<List<Collection>> = collectionDao.getAllCollections()

    suspend fun getCollectionById(id: Long): Collection? = collectionDao.getCollectionById(id)

    suspend fun insertCollection(collection: Collection): Long = collectionDao.insertCollection(collection)

    suspend fun updateCollection(collection: Collection) = collectionDao.updateCollection(collection)

    suspend fun deleteCollection(collection: Collection) = collectionDao.deleteCollection(collection)

    suspend fun deleteCollectionById(id: Long) = collectionDao.deleteCollectionById(id)

    // Collection item operations
    fun getItemsByCollectionId(collectionId: Long): Flow<List<CollectionItem>> =
        collectionItemDao.getItemsByCollectionId(collectionId)

    suspend fun getItemById(id: Long): CollectionItem? = collectionItemDao.getItemById(id)

    suspend fun insertItem(item: CollectionItem): Long = collectionItemDao.insertItem(item)

    suspend fun updateItem(item: CollectionItem) = collectionItemDao.updateItem(item)

    suspend fun deleteItem(item: CollectionItem) = collectionItemDao.deleteItem(item)

    suspend fun deleteItemById(id: Long) = collectionItemDao.deleteItemById(id)

    /**
     * جلب عناصر المجموعة مرة واحدة (للاستخدام في التصدير)
     */
    suspend fun getItemsByCollectionIdOnce(collectionId: Long): List<CollectionItem> {
        return collectionItemDao.getItemsByCollectionIdOnce(collectionId)
    }

    // Auto-generation
    suspend fun generateAutoCollection() {
        val autoCollections = listOf(
            "Автомобили" to listOf(
                CollectionItem(
                    collectionId = 0,
                    name = "Toyota Camry",
                    model = "2023",
                    description = "Седан бизнес-класса",
                    location = "Япония"
                ),
                CollectionItem(
                    collectionId = 0,
                    name = "BMW X5",
                    model = "2024",
                    description = "Премиальный внедорожник",
                    location = "Германия"
                ),
                CollectionItem(
                    collectionId = 0,
                    name = "Tesla Model 3",
                    model = "2023",
                    description = "Электрический седан",
                    location = "США"
                )
            ),
            "Смартфоны" to listOf(
                CollectionItem(
                    collectionId = 0,
                    name = "iPhone 15 Pro",
                    model = "2023",
                    description = "Флагманский смартфон Apple",
                    location = "США"
                ),
                CollectionItem(
                    collectionId = 0,
                    name = "Samsung Galaxy S24",
                    model = "2024",
                    description = "Флагманский смартфон Samsung",
                    location = "Южная Корея"
                )
            ),
            "Книги" to listOf(
                CollectionItem(
                    collectionId = 0,
                    name = "Война и мир",
                    model = "Лев Толстой",
                    description = "Роман-эпопея",
                    location = "Россия"
                ),
                CollectionItem(
                    collectionId = 0,
                    name = "1984",
                    model = "Джордж Оруэлл",
                    description = "Антиутопия",
                    location = "Великобритания"
                )
            )
        )

        val randomCollection = autoCollections.random()
        val collection = Collection(
            name = randomCollection.first,
            description = "Автоматически созданная коллекция",
            isAutoGenerated = true
        )

        val collectionId = insertCollection(collection)

        randomCollection.second.forEach { item ->
            insertItem(item.copy(collectionId = collectionId))
        }
    }
}